# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-01 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 11, 0, 33, 987481)),
        ),
    ]
