# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_auto_20181101_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPILead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('teams', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(upload_to='static/assets/img/profile_pics')),
                ('incidents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KPITeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=255)),
                ('incidents', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 12, 43, 32, 849012)),
        ),
    ]
