# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_auto_20181107_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 13, 7, 5, 287798)),
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='eft_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.KPILead'),
        ),
    ]
