# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_auto_20181107_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 13, 13, 43, 667584)),
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.KPITeam'),
        ),
    ]
