# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_auto_20181107_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiteam',
            name='eft_lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kpi.KPILead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 15, 2, 1, 177221)),
        ),
    ]
