# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_auto_20181107_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.KPICompany'),
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 10, 7, 18, 556622)),
        ),
    ]
