# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0008_auto_20181108_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 10, 9, 48, 593204)),
        ),
    ]
