# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0010_auto_20181108_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpilead',
            name='incidents',
        ),
        migrations.RemoveField(
            model_name='kpilead',
            name='teams',
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 10, 15, 5, 795347)),
        ),
    ]
