# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0011_auto_20181108_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiteam',
            name='incidents',
        ),
        migrations.RemoveField(
            model_name='kpiteam',
            name='members',
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 10, 16, 41, 670831)),
        ),
    ]
