# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0012_auto_20181108_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiteam',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kpi.KPICompany'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 13, 5, 52, 777441)),
        ),
    ]
