# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-13 05:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0013_auto_20181108_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 13, 7, 14, 2, 206579)),
        ),
    ]
