# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0016_auto_20181113_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='reportable',
            field=models.NullBooleanField(),
        ),
    ]
