# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-19 12:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0019_auto_20181119_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='eft_lead',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', on_delete=django.db.models.deletion.CASCADE, to='kpi.KPILead'),
        ),
        migrations.AlterField(
            model_name='kpiincidentreport',
            name='team_name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='eft_lead', chained_model_field='eft_lead', on_delete=django.db.models.deletion.CASCADE, to='kpi.KPITeam'),
        ),
    ]
