# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-22 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0020_auto_20181119_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpilead',
            name='profile_pic',
            field=models.ImageField(upload_to='kpi/static/assets/img/eftlead'),
        ),
    ]
