# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-22 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0022_auto_20181122_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpilead',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
