# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0024_auto_20181122_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpicompany',
            name='company_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='kpiteam',
            name='team_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='kpilead',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
